language: objective-c
osx_image: xcode9.1

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform iOS

script:
  # Workaround for Simulator getting stuck
  # See: https://github.com/travis-ci/travis-ci/issues/3040#issuecomment-146700203
  - open -b com.apple.iphonesimulator
  - ./bin/test
